import { generatePDF } from 'react-native-html-to-pdf';
import Share from 'react-native-share';
import { Platform, Alert } from 'react-native';

interface GenerateQuestionsPDFOptions {
  companyName: string;
  questions: string[];
  fileName?: string;
}

const generateQuestionsHTML = (
  companyName: string,
  questions: string[],
): string => {
  const questionItems = questions
    .map(
      (question, index) => `
      <div class="question-box">
        <span class="question-number">질문 ${index + 1}.</span>
        <span class="question-text">${question}</span>
      </div>
    `,
    )
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif;
          padding: 40px;
          background-color: #1a1a1a;
          color: white;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #3D9A5D;
        }
        .title {
          font-size: 24px;
          font-weight: bold;
          margin-bottom: 8px;
        }
        .subtitle {
          font-size: 14px;
          color: #888;
        }
        .company-name {
          color: #3D9A5D;
          font-weight: bold;
        }
        .question-box {
          background-color: #2a2a2a;
          border-radius: 8px;
          padding: 16px 20px;
          margin-bottom: 12px;
        }
        .question-number {
          color: #3D9A5D;
          font-weight: bold;
          margin-right: 8px;
        }
        .question-text {
          font-size: 14px;
          line-height: 1.6;
        }
        .footer {
          text-align: center;
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #333;
          font-size: 12px;
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">
          <span class="company-name">${companyName}</span> 면접 예상 질문
        </div>
        <div class="subtitle">TikiTaka AI가 생성한 맞춤형 면접 질문</div>
      </div>

      ${questionItems}

      <div class="footer">
        Generated by TikiTaka - ${new Date().toLocaleDateString('ko-KR')}
      </div>
    </body>
    </html>
  `;
};

export const generateQuestionsPDF = async ({
  companyName,
  questions,
  fileName,
}: GenerateQuestionsPDFOptions): Promise<string | null> => {
  try {
    const html = generateQuestionsHTML(companyName, questions);
    const pdfFileName =
      fileName || `tikitaka_${companyName}_면접질문_${Date.now()}`;

    const options = {
      html,
      fileName: pdfFileName,
      directory: Platform.OS === 'ios' ? 'Documents' : 'Download',
    };

    const file = await generatePDF(options);
    return file.filePath || null;
  } catch (error) {
    console.error('PDF 생성 실패:', error);
    return null;
  }
};

export const downloadAndSharePDF = async ({
  companyName,
  questions,
}: GenerateQuestionsPDFOptions): Promise<void> => {
  try {
    const filePath = await generateQuestionsPDF({ companyName, questions });

    if (!filePath) {
      Alert.alert('오류', 'PDF 생성에 실패했습니다.');
      return;
    }

    await Share.open({
      url: Platform.OS === 'ios' ? filePath : `file://${filePath}`,
      type: 'application/pdf',
      title: `${companyName} 면접 질문`,
    });
  } catch (error: any) {
    if (error?.message !== 'User did not share') {
      console.error('PDF 공유 실패:', error);
      Alert.alert('오류', 'PDF 공유에 실패했습니다.');
    }
  }
};
